### ISSUE TITLE
ROS Indigo weird TF errors

### ISSUE THREAD

**Issue by atasoglou** [pal-robotics/aruco_ros#54]
Hello I am trying to use this with a simple `image_raw` and `camera_info` topic but I am always getting the following errors:

`TF_NAN_INPUT: Ignoring transform for child_frame_id "marker_frame" from authority "unknown_publisher" because of a nan value in the transform (-nan -inf -nan) (-0.542478 -0.431334 0.485505 0.532872) at line 244 in /tmp/binarydeb/ros-indigo-tf2-0.5.17/src/buffer_core.cpp`

So it seems there is some rotation calculation but no translation. 

I am using:
```
<arg name="marker_frame"    default="marker_frame"/>
<arg name="ref_frame"       default=""/>  <!-- leave empty and the pose will be published wrt param parent_name -->
<param name="camera_frame"       value="base_link"/>
```
This is just the simple example. I used it with our robots tf-publisher as well, where the camera_frame was linked to the rest of the robot, but still the same issue.

Looking at the image `/aruco_single/result` I can see a valid detection.

Any idea what is happening?

**Comment by awesomebytes** [comment]
Maybe your camera info is wrong or empty?

**Comment by atasoglou** [comment]
Hmm, which field do you have in mind? Maybe the frame in the header of the camera info?
Here is the camera info:
```
header: 
  seq: 1699
  stamp: 
    secs: 1528207593
    nsecs: 3959129088
  frame_id: camera_mlx_frame_link
height: 512
width: 1024
distortion_model: plumb_bob
D: [-0.37344000000000005, 0.13855, -0.023670000000000004, -0.00028000000000000003, 0.00062]
K: [551.29784, 0.0, 0.0, -0.27212000000000003, 551.16795, 0.0, 501.52976, 248.17503, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [551.29784, 0.0, 0.0, -0.27212000000000003, 551.16795, 0.0, 501.52976, 248.17503, 1.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
