### ISSUE TITLE
Wrong pose of aruco tag after upgrade to ros noetic

### ISSUE THREAD

**Issue by Hmueller-hako** [pal-robotics/aruco_ros#98]
We have migrated our software from ROS Melodic to ROS Noetic. I noticed that the pose from the Aruco tag is no longer correct. Also, the coordinate system in the result image is drawn in the wrong position (similar to https://github.com/pal-robotics/aruco_ros/issues/89#issuecomment-777649188) .

With version 2.0.2:
![aruco_rviz_2 0 2](https://user-images.githubusercontent.com/99403986/153416073-fbefc499-0316-4036-a85c-2898d5f3e5e4.png)

With commit 52c8c2bd4e9f60b6ff6a55e9470ba879fb5158ef : 
![aruco_rviz_52c8c2bd4e9f60b6ff6a55e9470ba879fb5158ef](https://user-images.githubusercontent.com/99403986/153416627-6344d0fc-39a1-4680-b300-09ba3f30403b.png)

I use the following launch-file:
`<launch>

    <arg name="markerSize"      default="0.11"/>    
    <arg name="side"             default="front"/>
    <arg name="ref_frame"       default="camera_$(arg side)_depth_optical_frame"/>  

    <node pkg="aruco_ros" type="marker_publisher" name="aruco_marker_publisher_$(arg side)_camera">
        <remap from="/camera_info" to="/camera_$(arg side)/color/camera_info" />
        <remap from="/image" to="/camera_$(arg side)/color/image_raw" />
        <remap from="~/markers" to="/aruco/markers" />
        <param name="image_is_rectified" value="False"/>
        <param name="marker_size"        value="$(arg markerSize)"/>
        <param name="reference_frame"    value="$(arg ref_frame)"/>   
        <param name="camera_frame"       value="camera_$(arg side)_depth_optical_frame"/>
    </node>

</launch>
```
The camera_info-message
`rostopic echo -n 1 /camera_front/color/camera_info 
header: 
  seq: 13528
  stamp: 
    secs: 4155
    nsecs: 142000000
  frame_id: "camera_front_depth_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [319.9988245765257, 0.0, 320.5, 0.0, 319.9988245765257, 240.5, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [319.9988245765257, 0.0, 320.5, -0.0, 0.0, 319.9988245765257, 240.5, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
